spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  # druid
  datasource:
    url: jdbc:mysql://172.16.179.133:3306/shop?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=Asia/Shanghai
    username: root1
    password: 123456

mybatis-plus:
  mapper-locations: classpath*:org/imooc/mall/mapper/xml/*.xml
  global-config:
    id-type: 0 #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: true
    refresh-mapper: true
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true

jwt:
  header: Authorization   #http请求头所需要的字段
  secret: h72PfeKvUAzT5gMQ        #jwt秘钥
  expiration: 31536000      #7天 单位:秒
  auth-path: /auth        #认证请求的路径
  md5-key: r8klNBcKVvFO0sbT      #md5加密混淆key
